development:
  max_profile_id: 1
  mkc_wordpress_feed_url: http://maxkeiser.com/category/pirate-myfilm/feed

test:
  max_profile_id: 2
  mkc_wordpress_feed_url: http://maxkeiser.com/category/pirate-myfilm/feed

production:
  max_profile_id: 2
  mkc_wordpress_feed_url: http://maxkeiser.com/category/pirate-myfilm/feed

