development:
  #this is actually the pmf fund user id (need to change the property name eventually)
  max_profile_id: 9
  maxriot_profile_id: 2
  mkc_wordpress_feed_url: http://maxkeiser.com/category/pirate-myfilm/feed
  paypal_button_submission_url: https://www.sandbox.paypal.com/cgi-bin/webscr
  max_wp_login_name: blah
  max_wp_login_pw: blah

test:
  max_profile_id: 9
  maxriot_profile_id: 10
  mkc_wordpress_feed_url: http://maxkeiser.com/category/pirate-myfilm/feed
  paypal_button_submission_url: https://www.sandbox.paypal.com/cgi-bin/webscr
  max_wp_login_name: blah
  max_wp_login_pw: blah

production:
  #this is actually the pmf fund user id (need to change the property name eventually)
  max_profile_id: 2
  maxriot_profile_id: 7
  mkc_wordpress_feed_url: http://maxkeiser.com/category/pirate-myfilm/feed
  paypal_button_submission_url: https://www.paypal.com/cgi-bin/webscr
  max_wp_login_name: maxkeiser
  max_wp_login_pw: h0llyw00d

