development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: piratemyfilm1_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: piratemyfilm1_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock